name: 🦕 releasaurus
description: Releasaurus worflow to fully manage release process for gitea repositories
inputs:
  repo:
    description: The gitea repo to affect
    default: ${{ gitea.server_url }}/${{ gitea.repository }}
  token:
    description: The gitea token to use. This token will need privileges to create PRs, tags, labels, and releases
  debug:
    description: Enables debug logs
    default: ""
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: robgonnella/releasaurus/action/gitea/release@${{ github.action_ref }}
      if: "${{ startsWith(gitea.event.head_commit.message, format('chore({0}): release', gitea.event.repository.default_branch)) }}"
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
    - uses: robgonnella/releasaurus/action/gitea/release-pr@${{ github.action_ref }}
      if: "${{ !startsWith(gitea.event.head_commit.message, format('chore({0}): release', gitea.event.repository.default_branch)) }}"
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
