name: 🦕 releasaurus
description: Releasaurus worflow to fully manage release process for gitea repositories
inputs:
  repo:
    description: The gitea repo to affect
    default: ${{ gitea.server_url }}/${{ gitea.repository }}
  token:
    description: The gitea token to use. This token will need privileges to create PRs, tags, labels, and releases
  debug:
    description: Enables debug logs
    default: ""
outputs: {}
runs:
  using: "composite"
  steps:
    - name: check commit
      id: check_commit
      shell: bash
      run: |
        if [[ "${{ gitea.event.head_commit.message }}" =~ "^chore.*: release.+" ]]; then
            echo "is_release_commit=true" >> $GITEA_OUTPUT
        else
          echo "is_release_commit=false" >> $GITEA_OUTPUT
        fi
    - uses: robgonnella/releasaurus/action/gitea/release@v0.8.0
      if: ${{ steps.check_commit.outputs.is_release_commit == 'true' }}
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
    - uses: robgonnella/releasaurus/action/gitea/release-pr@v0.8.0
      if: ${{ steps.check_commit.outputs.is_release_commit == 'false' }}
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
