[env]
_.file = ".env"

[tools]
just = "1.49.0"

# rust automatically configured from rust-toolchain.toml
[settings]
idiomatic_version_file_enable_tools = ["rust"]

[hooks]
postinstall = """
if ! cargo llvm-cov --help >/dev/null 2>&1; then
  cargo install cargo-llvm-cov
fi
if ! cargo machete --help >/dev/null 2>&1; then
  cargo install cargo-machete
fi
if ! command -v mdbook >/dev/null 2>&1; then
  cargo install mdbook
fi
"""
