#:schema ./schema/schema.json

[repository]
tag_search_depth = 25

[global.changelog]
include_author = true
aggregate_prereleases = true

[global.changelog.named_parsers]
ci.skip = true
chore.skip = true
miscellaneous.skip = false

[global.prerelease]
strategy = "versioned"
suffix = "rc"

[[package]]
name = "workspace"
tag_prefix = "v"
release_type = "rust"
additional_manifest_files = [
  { path = "./action/action.yml", version_regex = "(?m)v(?<version>\\d+\\.\\d+\\.\\d+-?.*?)-alpine$" }
]
sub_packages = [
  { name = "releasaurus", path = "crates/cli", release_type = "rust" },
  { name = "releasaurus-core", path = "crates/core", release_type = "rust" }
]
