name: 🦕 releasaurus release
description: Runs "releasaurus release" to automate tagging and release creation for github repositories
inputs:
  repo:
    description: The github repo to affect
    default: ${{ github.server_url }}/${{ github.repository }}
  token:
    description: The github token to use. This token will need privileges to create PRs, tags, labels, and releases
  debug:
    description: Enables debug logs
    default: ""
outputs: {}
runs:
  using: docker
  image: docker://rgonnella/releasaurus:v0.4.8
  env:
    RELEASAURUS_DEBUG: ${{ inputs.debug }}
  args:
    - release
    - --github-repo
    - ${{ inputs.repo }}
    - --github-token
    - ${{ inputs.token }}
