use clap::{Parser, Subcommand, ValueEnum};

#[derive(Subcommand, Debug)]
pub enum Command {
    TagAuthors {
        /// The platform to target
        #[arg(short, long, value_enum)]
        platform: Platform,

        /// token for authenticating to target platform. Can also be set via
        /// env var as <PLATFORM>_TOKEN
        #[arg(short, long)]
        token: Option<String>,

        /// Path to the release json file generated by
        /// "releasaurus show next-release -o <file>.json"
        #[arg(short, long)]
        file: String,

        /// The file path to write output json to.
        /// This should have .json extension
        #[arg(short, long)]
        out_file: String,
    },
}

#[derive(Debug, Clone, ValueEnum)]
pub enum Platform {
    Slack,
}

/// CLI arguments
#[derive(Parser, Debug)]
#[command(version, about)]
pub struct Cli {
    /// Enable debug logging
    #[arg(long, default_value_t = false, global = true)]
    pub debug: bool,

    /// Subcommand to execute
    #[command(subcommand)]
    pub command: Command,
}
