//! Configuration for changelog generation and commit analysis.

use crate::analyzer::types::Tag;

/// Default changelog body template.
pub const DEFAULT_BODY: &str = r#"# [{{ version  }}]({{ link }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | filter(attribute="merge_commit", value=false) | sort(attribute="group") | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
{% if commit.breaking -%}
{% if commit.scope %}_({{ commit.scope }})_ {% endif -%}[**breaking**]: {{ commit.message }} [_({{ commit.id | truncate(length=8, end="") }})_]({{ commit.link }})
{% if commit.body -%}
> {{ commit.body }}
{% endif -%}
{% if commit.breaking_description -%}
> {{ commit.breaking_description }}
{% endif -%}
{% else -%}
- {% if commit.scope %}_({{ commit.scope }})_ {% endif %}{{ commit.message }} [_({{ commit.id | truncate(length=8, end="") }})_]({{ commit.link }})
{% endif -%}
{% endfor %}
{% endfor %}
 "#;

pub const DEFAULT_FOOTER: &str = "Generated by Releasaurus 🦕";

/// Configuration for commit analysis and changelog generation.
#[derive(Debug, Clone)]
pub struct AnalyzerConfig {
    /// Path to cloned repository.
    pub repo_path: String,
    /// Path to package directory within repository.
    pub package_relative_path: String,
    /// Tera template string for changelog body format.
    pub body: String,
    /// Optional Tera template for changelog header.
    pub header: Option<String>,
    /// Optional Tera template for changelog footer.
    pub footer: Option<String>,
    /// Optional prefix for package tags.
    pub tag_prefix: Option<String>,
    /// Base URL for commit links in changelog.
    pub commit_link_base_url: String,
    /// Base URL for release links in changelog.
    pub release_link_base_url: String,
    /// Only process commits since this tag.
    pub starting_tag: Option<Tag>,
}

impl Default for AnalyzerConfig {
    fn default() -> Self {
        Self {
            repo_path: ".".into(),
            package_relative_path: ".".into(),
            body: DEFAULT_BODY.into(),
            header: None,
            footer: Some(DEFAULT_FOOTER.into()),
            tag_prefix: None,
            starting_tag: None,
            commit_link_base_url: "".into(),
            release_link_base_url: "".into(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_defaults() {
        let config = AnalyzerConfig::default();
        assert!(!config.body.is_empty())
    }
}
