use crate::{
    Result,
    config::{
        manifest::{ManifestFile, gen_package_path, gen_workspace_path},
        package::PackageConfig,
    },
    forge::manager::ForgeManager,
};

pub struct RustManifestLoader {}

impl RustManifestLoader {
    pub async fn load_manifests(
        forge: &ForgeManager,
        pkg: &PackageConfig,
    ) -> Result<Option<Vec<ManifestFile>>> {
        let cargo_toml_pkg_path = gen_package_path(pkg, "Cargo.toml");
        let cargo_toml_workspace_path = gen_workspace_path(pkg, "Cargo.toml");
        let is_workspace = cargo_toml_pkg_path == cargo_toml_workspace_path;

        let package_files = vec!["Cargo.toml", "Cargo.lock"];
        let workspace_files = vec!["Cargo.lock"];
        let mut manifests = vec![];

        for file in package_files {
            let full_path = gen_package_path(pkg, file);
            if let Some(content) = forge.get_file_content(&full_path).await? {
                manifests.push(ManifestFile {
                    file_path: full_path,
                    file_basename: file.to_string(),
                    is_workspace: false,
                    content,
                });
            }
        }

        if is_workspace {
            for file in workspace_files {
                let full_path = gen_workspace_path(pkg, file);
                if let Some(content) =
                    forge.get_file_content(&full_path).await?
                {
                    manifests.push(ManifestFile {
                        file_path: full_path,
                        file_basename: file.to_string(),
                        is_workspace: true,
                        content,
                    });
                }
            }
        }

        if manifests.is_empty() {
            return Ok(None);
        }

        Ok(Some(manifests))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        forge::traits::MockForge, test_helpers::create_test_remote_config,
    };

    // ===== Test Helpers =====

    fn package_config(path: &str, workspace_root: &str) -> PackageConfig {
        PackageConfig {
            name: "my-package".to_string(),
            path: path.to_string(),
            workspace_root: workspace_root.to_string(),
            release_type: None,
            tag_prefix: None,
            prerelease: None,
            additional_paths: None,
            additional_manifest_files: None,
            breaking_always_increment_major: None,
            features_always_increment_minor: None,
            custom_major_increment_regex: None,
            custom_minor_increment_regex: None,
        }
    }

    fn mock_forge_with_file(path: &str, content: &str) -> ForgeManager {
        let mut mock = MockForge::new();
        let path = path.to_string();
        let content = content.to_string();
        mock.expect_get_file_content().returning(move |p| {
            if p == path {
                Ok(Some(content.clone()))
            } else {
                Ok(None)
            }
        });
        mock.expect_remote_config()
            .returning(create_test_remote_config);
        ForgeManager::new(Box::new(mock))
    }

    fn mock_forge_empty() -> ForgeManager {
        let mut mock = MockForge::new();
        mock.expect_get_file_content().returning(|_| Ok(None));
        mock.expect_remote_config()
            .returning(create_test_remote_config);
        ForgeManager::new(Box::new(mock))
    }

    // ===== Manifest Loading Tests =====

    #[tokio::test]
    async fn loads_cargo_toml() {
        let pkg = package_config(".", ".");
        let forge = mock_forge_with_file(
            "Cargo.toml",
            r#"[package]
name = "my-package"
version = "1.0.0""#,
        );

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_some());
        let manifests = result.unwrap();
        assert_eq!(manifests.len(), 1);
        assert_eq!(manifests[0].file_basename, "Cargo.toml");
        assert!(!manifests[0].is_workspace);
    }

    #[tokio::test]
    async fn loads_cargo_lock() {
        let pkg = package_config(".", ".");
        let forge = mock_forge_with_file(
            "Cargo.lock",
            r#"# This file is automatically generated
[[package]]
name = "my-package"
version = "1.0.0""#,
        );

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_some());
        let manifests = result.unwrap();
        assert_eq!(manifests[0].file_basename, "Cargo.lock");
    }

    #[tokio::test]
    async fn loads_multiple_manifests_in_subpackage() {
        let pkg = package_config("crates/my-crate", ".");
        let mut mock = MockForge::new();
        mock.expect_get_file_content().returning(|path| {
            if path == "crates/my-crate/Cargo.toml" {
                Ok(Some("[package]\nversion = \"1.0.0\"".to_string()))
            } else if path == "crates/my-crate/Cargo.lock" {
                Ok(Some("[[package]]\nversion = \"1.0.0\"".to_string()))
            } else {
                Ok(None)
            }
        });
        mock.expect_remote_config()
            .returning(create_test_remote_config);
        let forge = ForgeManager::new(Box::new(mock));

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_some());
        let manifests = result.unwrap();
        assert_eq!(manifests.len(), 2);
    }

    #[tokio::test]
    async fn loads_workspace_files_for_root_package() {
        let pkg = package_config(".", ".");
        let mut mock = MockForge::new();
        mock.expect_get_file_content().returning(|path| {
            if path == "Cargo.toml" {
                Ok(Some("[package]\nversion = \"1.0.0\"".to_string()))
            } else if path == "Cargo.lock" {
                Ok(Some("[[package]]\nversion = \"1.0.0\"".to_string()))
            } else {
                Ok(None)
            }
        });
        mock.expect_remote_config()
            .returning(create_test_remote_config);
        let forge = ForgeManager::new(Box::new(mock));

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_some());
        let manifests = result.unwrap();
        // Should have both files, with workspace lock marked
        assert!(!manifests.is_empty());
        let workspace_locks =
            manifests.iter().filter(|m| m.is_workspace).count();
        assert_eq!(workspace_locks, 1);
    }

    #[tokio::test]
    async fn does_not_load_workspace_files_for_subpackage() {
        let pkg = package_config("crates/my-crate", ".");
        let forge =
            mock_forge_with_file("crates/my-crate/Cargo.toml", "[package]");

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_some());
        let manifests = result.unwrap();
        // All manifests should be non-workspace
        assert!(manifests.iter().all(|m| !m.is_workspace));
    }

    #[tokio::test]
    async fn returns_none_when_no_manifests_found() {
        let pkg = package_config(".", ".");
        let forge = mock_forge_empty();

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_none());
    }

    #[tokio::test]
    async fn uses_correct_path_for_subpackage() {
        let pkg = package_config("crates/my-rust-lib", ".");
        let forge =
            mock_forge_with_file("crates/my-rust-lib/Cargo.toml", "[package]");

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_some());
        let manifests = result.unwrap();
        assert_eq!(manifests[0].file_path, "crates/my-rust-lib/Cargo.toml");
    }

    #[tokio::test]
    async fn uses_correct_path_with_workspace_root() {
        let pkg = package_config("src", "workspace");
        let forge =
            mock_forge_with_file("workspace/src/Cargo.toml", "[package]");

        let result = RustManifestLoader::load_manifests(&forge, &pkg)
            .await
            .unwrap();

        assert!(result.is_some());
        let manifests = result.unwrap();
        assert_eq!(manifests[0].file_path, "workspace/src/Cargo.toml");
    }
}
