name: 🦕 releasaurus
description: Releasaurus worflow to fully manage release process for github repositories
inputs:
  repo:
    description: The github repo to affect
    default: ${{ github.server_url }}/${{ github.repository }}
  token:
    description: The github token to use. This token will need privileges to create PRs, tags, labels, and releases
  debug:
    description: Enables debug logs
    default: ""
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: robgonnella/releasaurus/action/github/release@v0.4.12
      if: "${{ startsWith(github.event.head_commit.message, format('chore({0}): release', github.event.repository.default_branch)) }}"
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
    - uses: robgonnella/releasaurus/action/github/release-pr@v0.4.12
      if: "${{ !startsWith(github.event.head_commit.message, format('chore({0}): release', github.event.repository.default_branch)) }}"
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
