name: 🦕 releasaurus
description: Releasaurus worflow to fully manage release process for github repositories
inputs:
  repo:
    description: The github repo to affect
    default: ${{ github.server_url }}/${{ github.repository }}
  token:
    description: The github token to use. This token will need privileges to create PRs, tags, labels, and releases
  debug:
    description: Enables debug logs
    default: ""
  git_user_name:
    description: The git user name to use when committing and creating tags
    default: "ReleasaurusCI"
  git_user_email:
    description: The git user email to use when committing and creating tags
    default: releasaurus-ci@noreply.com
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: robgonnella/releasaurus/action/github/release@v0.3.7
      if: "startsWith('${{ github.event.head_commit.message }}', 'chore(${{ github.event.repository.default_branch }}): release')"
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
        git_user_name: ${{ inputs.git_user_name }}
        git_user_email: ${{ inputs.git_user_email }}
    - uses: robgonnella/releasaurus/action/github/release-pr@v0.3.7
      if: "!startsWith('${{ github.event.head_commit.message }}', 'chore(${{ github.event.repository.default_branch }}): release')"
      with:
        repo: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        debug: ${{ inputs.debug }}
        git_user_name: ${{ inputs.git_user_name }}
        git_user_email: ${{ inputs.git_user_email }}
#
