name: publish

on:
  workflow_dispatch:

jobs:
  publish-docs:
    if: ${{ github.repository == 'robgonnella/releasaurus' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: peaceiris/actions-mdbook@v2
      - run: cd book && mdbook build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/build
          cname: releasaurus.rgon.io
