name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-unit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
        with:
          include_llvm_cov: "true"
          cache_policy: pull-push
      - name: test
        run: |
          cargo llvm-cov --ignore-filename-regex "(_test\.rs$)|(_tests\.rs$)"

  test_all:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
        with:
          include_llvm_cov: "true"
          cache_policy: pull-push
      - name: test
        env:
          GITHUB_TEST_REPO: ${{ vars.GH_TEST_REPO }}
          GITHUB_TEST_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
          GITHUB_RESET_SHA: ${{ vars.GH_RESET_SHA }}
          GITLAB_TEST_REPO: ${{ vars.GL_TEST_REPO }}
          GITLAB_TEST_TOKEN: ${{ secrets.GL_TEST_TOKEN }}
          GITLAB_RESET_SHA: ${{ vars.GL_RESET_SHA }}
          GITEA_TEST_REPO: ${{ vars.GT_TEST_REPO }}
          GITEA_TEST_TOKEN: ${{ secrets.GT_TEST_TOKEN }}
          GITEA_RESET_SHA: ${{ vars.GT_RESET_SHA }}
          FORGEJO_TEST_REPO: ${{ vars.FJ_TEST_REPO }}
          FORGEJO_TEST_TOKEN: ${{ secrets.FJ_TEST_TOKEN }}
          FORGEJO_RESET_SHA: ${{ vars.FJ_RESET_SHA }}
          AZURE_DEVOPS_TEST_REPO: ${{ vars.AZDO_TEST_REPO }}
          AZURE_DEVOPS_TEST_TOKEN: ${{ secrets.AZDO_TEST_TOKEN }}
          AZURE_DEVOPS_RESET_SHA: ${{ vars.AZDO_RESET_SHA }}
        run: |
          cargo llvm-cov \
            --ignore-filename-regex "(_test\.rs$)|(_tests\.rs$)" \
            --features _integration_tests -- --nocapture
